export const Strings = {
  // App
  appName: 'TF Tracker',
  appTagline: 'שליטה מלאה בכף היד שלך',

  // Tab names
  tabDashboard: 'דף הבית',
  tabNutrition: 'תזונה',
  tabWorkout: 'אימון',
  tabMetrics: 'מדדים',
  tabChat: "צ'אט",

  // Dashboard
  greeting: 'שלום,',
  caloriesRemaining: 'קלוריות נותרות',
  outOf: 'מתוך',
  kcal: 'קק"ל',
  dailyTargets: 'יעדים יומיים',
  protein: 'חלבון',
  carbs: 'פחמימה',
  fat: 'שומן',
  nextMeal: 'ארוחה הבאה',
  plannedWorkout: 'אימון מתוכנן',
  noMealPlanned: 'אין ארוחה מתוכננת',
  noWorkoutPlanned: 'אין אימון מתוכנן',

  // Nutrition
  todaysMealPlan: 'תפריט היום',
  breakfast: 'ארוחת בוקר',
  morningSnack: 'נשנוש בוקר',
  lunch: 'ארוחת צהריים',
  afternoonSnack: 'נשנוש אחה"צ',
  dinner: 'ארוחת ערב',
  eveningSnack: 'נשנוש ערב',
  alternatives: 'תחליפים',
  recipes: 'מתכונים',
  calorieCalculator: 'מחשבון קלוריות',
  macroCalculator: 'מחשבון מאקרו',
  grams: 'גרם',
  perServing: 'למנה',

  // Workout
  todaysWorkout: 'אימון היום',
  sets: 'סטים',
  reps: 'חזרות',
  weight: 'משקל',
  kg: 'ק"ג',
  rest: 'מנוחה',
  seconds: 'שניות',
  minutes: 'דקות',
  watchVideo: 'צפה בסרטון',
  logSet: 'רשום סט',
  completed: 'הושלם',
  exercisesCount: 'תרגילים',
  duration: 'משך',
  startWorkout: 'התחל אימון',

  // Metrics
  weightTracking: 'מעקב משקל',
  bodyFat: 'אחוזי שומן',
  measurements: 'מדידות',
  addWeight: 'הוסף שקילה',
  addMeasurement: 'הוסף מדידה',
  chest: 'חזה',
  waist: 'מותניים',
  hips: 'ירכיים',
  arm: 'זרוע',
  thigh: 'ירך',
  progressPhotos: 'תמונות התקדמות',
  addPhoto: 'הוסף תמונה',
  lastWeek: 'שבוע אחרון',
  lastMonth: 'חודש אחרון',
  last3Months: '3 חודשים',
  last6Months: '6 חודשים',
  allTime: 'הכל',

  // Chat
  typeMessage: 'כתוב הודעה...',
  send: 'שלח',
  chatPremiumOnly: "שדרג לפרימיום לגישה לצ'אט ישיר עם תומר",
  online: 'מחובר',
  offline: 'לא מחובר',
  lastSeen: 'נראה לאחרונה',

  // Auth
  login: 'התחבר',
  register: 'הרשם',
  email: 'אימייל',
  password: 'סיסמה',
  confirmPassword: 'אימות סיסמה',
  fullName: 'שם מלא',
  forgotPassword: 'שכחת סיסמה?',
  resetPassword: 'איפוס סיסמה',
  or: 'או',
  continueWithGoogle: 'המשך עם Google',
  continueWithApple: 'המשך עם Apple',
  alreadyHaveAccount: 'כבר יש לך חשבון?',
  dontHaveAccount: 'אין לך חשבון?',
  signUp: 'הירשם',

  // Onboarding
  onboarding1Title: 'ברוך הבא ל-TF Tracker',
  onboarding1Subtitle: 'התפריט, תכנית האימונים והמעקב — הכל באפליקציה אחת.',
  onboarding2Title: 'מעקב פשוט וחכם',
  onboarding2Subtitle: 'עקוב אחרי הקלוריות, המאקרו, המשקל וההתקדמות שלך בקלות.',
  onboarding3Title: 'מותאם בדיוק בשבילך',
  onboarding3Subtitle: 'תומר פרידמן, תזונאי קליני עם 22 שנות ניסיון, בונה לך מערכת אישית.',
  getStarted: 'בוא נתחיל',
  skip: 'דלג',
  next: 'הבא',

  // Premium / Subscription
  upgradeToPremium: 'שדרג לפרימיום',
  premiumFeature: 'תכונה זו זמינה למנויי פרימיום',
  freeMonth: 'החודש הראשון חינם',
  thenPerMonth: 'אחר כך ₪39/חודש',
  subscribe: 'הרשם למנוי',
  cancelAnytime: 'ביטול בכל רגע, ללא התחייבות',
  currentPlan: 'המנוי הנוכחי שלך',
  freePlan: 'חינם',
  premiumPlan: 'פרימיום',
  coachingPlan: 'ליווי אישי',

  // Settings
  settings: 'הגדרות',
  profile: 'פרופיל',
  notifications: 'התראות',
  subscription: 'מנוי',
  about: 'אודות',
  logout: 'התנתק',
  deleteAccount: 'מחק חשבון',
  language: 'שפה',
  units: 'יחידות מידה',
  darkMode: 'מצב כהה',

  // General
  save: 'שמור',
  cancel: 'ביטול',
  delete: 'מחק',
  edit: 'ערוך',
  today: 'היום',
  yesterday: 'אתמול',
  loading: 'טוען...',
  error: 'שגיאה',
  retry: 'נסה שוב',
  noData: 'אין נתונים',
  cm: 'ס"מ',
  pct: '%',
};
